"""Different augmentations to choose."""
INTERPOLATION = "interpolation"
EXTRAPOLATION = "extrapolation"
NOISE = "noise"
EXTRAPOLATION_NOISE = "noise_extra"
INTERPOLATION_NOISE = "noise_inter"
FORWARD = "forward"
RANDOM_NOISE = "random_noise"
