"""Different augmentations to choose."""
INTERPOLATION = "interpolation"
EXTRAPOLATION = "extrapolation"
REPARAMETRIZATION = "reparametrization"
ADD_NOISE = "add_noise"
NORMAL_NOISE = "normal_noise"
UNIFORM_NOISE = "normal_noise"
DISTRIBUTION = "distribution"
